- name: "Update Arch Linux mirrorlist"
  include_tasks: update_archlinux.yml
  listen: "update-arch-linux-mirrorlist"
  vars:
    mirrors_file: "{{ repo_servers_dir }}/{{ repo_servers_filename }}"
    mirrors_bkup: "{{ repo_servers_dir }}/{{ repo_servers_bkup_filename }}"

