- name: "Create backup copy of mirror-list"
  copy:
    src: "{{ mirrors_file }}"
    dest: "{{ mirrors_bkup }}"
    force: yes
  become: true
  become_user: root

- name: "Find fastest servers, and replace the current mirror-list"
  command: reflector --country 'United States'
                     --latest '200'
                     --age '12'
                     --protocol 'http'
                     --protocol 'https'
                     --sort 'rate'
                     --save {{ mirrors_file|quote }}
  become: true
  become_user: root

