- name: "Create backup copy of mirror-list"
  ansible.builtin.copy:
    src: "{{ mirrors_file }}"
    dest: "{{ mirrors_bkup }}"
    force: yes
  become: true
  become_user: root

- name: "Find fastest servers, and replace the current mirror-list"
  ansible.builtin.service:
    name: reflector
    state: started
  become: true
  become_user: root

