- name: "Install 'reflector' package, for mirrorlist update support"
  community.general.pacman:
    name: reflector
    state: present
  become: true
  become_user: root

- name: "Install 'pacman-contrib' and 'gvim' packages, for package management"
  community.general.pacman:
    # NOTE: install gvim, for vim copy/paste support
    name:
      - pacman-contrib
      - gvim
    state: present
  become: true
  become_user: root

- name: "Create '/usr/local/bin/' utility scripts"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "{{ script_name }}.j2"
    owner: 'root'
    group: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root
  loop:
    - 'do_mirrors_sysupgrade'
    - 'do_package_cleanup'
    - 'do_pacnew_merge'
  loop_control:
    loop_var: script_name

