- name: "Install reflector package"
  include_tasks: archlinux/install_reflector.yml

- name: "Check repo-server-list age, and update as required"
  include_tasks: archlinux/check_and_update.yml

- name: "Remove 'pacman-mirrorlist' package, since reflector is used"
  include_tasks: archlinux/rem_mirrorlist_pkg.yml

