- name: "Install 'reflector' package"
  community.general.pacman:
    name: reflector
    state: present
  become: true
  become_user: root

- name: "Install 'pacman-contrib' package"
  community.general.pacman:
    name: pacman-contrib
    state: present
  become: true
  become_user: root

- name: "Create '/usr/local/bin/{{ script_name }}.sh' utility script"
  ansible.builtin.template:
    dest: "/usr/local/bin/{{ script_name }}.sh"
    src: "{{ script_name }}.j2"
    owner: 'root'
    group: 'root'
    mode: '755'
    force: yes
  become: true
  become_user: root
  loop:
    - 'do_mirrors_sysupgrade'
    - 'do_package_cleanup'
  loop_control:
    loop_var: script_name

